// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBosmPQwCvquPSQtk-2_gCS8IDOjLhNr3s',
    appId: '1:277039437960:android:867c160c3a176f115f673d',
    messagingSenderId: '277039437960',
    projectId: 'we-chat-5c28e',
    storageBucket: 'we-chat-5c28e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYZGK9PnOy-4R6w3ViLB5emVY48JIECmY',
    appId: '1:277039437960:ios:fa1eb28ab1fd42f75f673d',
    messagingSenderId: '277039437960',
    projectId: 'we-chat-5c28e',
    storageBucket: 'we-chat-5c28e.firebasestorage.app',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu_4-S5KrOydmXHUOF-m-haxSOto4J3j4',
    appId: '1:277039437960:web:f8e64404929a04c35f673d',
    messagingSenderId: '277039437960',
    projectId: 'we-chat-5c28e',
    authDomain: 'we-chat-5c28e.firebaseapp.com',
    storageBucket: 'we-chat-5c28e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYZGK9PnOy-4R6w3ViLB5emVY48JIECmY',
    appId: '1:277039437960:ios:fa1eb28ab1fd42f75f673d',
    messagingSenderId: '277039437960',
    projectId: 'we-chat-5c28e',
    storageBucket: 'we-chat-5c28e.firebasestorage.app',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu_4-S5KrOydmXHUOF-m-haxSOto4J3j4',
    appId: '1:277039437960:web:79b7bb93021486d85f673d',
    messagingSenderId: '277039437960',
    projectId: 'we-chat-5c28e',
    authDomain: 'we-chat-5c28e.firebaseapp.com',
    storageBucket: 'we-chat-5c28e.firebasestorage.app',
  );

}